### ISSUE TITLE
something error

### ISSUE THREAD

**Issue by yanglaichang24** [dstore-dbap/logstash-output-webhdfs-discontinued#5]
![image](https://cloud.githubusercontent.com/assets/17734824/13871882/0845e040-ed21-11e5-924a-540e8a1860bf.png)

**Comment by dstore-dbap** [comment]
Hi yanglaichang24,

please note that this repository is discontinued. Current development for this plugin can be found @https://github.com/logstash-plugins/logstash-output-webhdfs. Please test the current version there and see if your error still persists. If so, please open an issue there.

I'm going to close the issue here.

Thanks and take care,
Björn

**Comment by yanglaichang24** [comment]
thands



yanglaichang24@sina.com
 
From: Björn
Date: 2016-03-21 16:54
To: dstore-dbap/logstash-output-webhdfs-discontinued
CC: Matches Man
Subject: Re: [logstash-output-webhdfs-discontinued] something error (#5)
Hi yanglaichang24,
please note that this repository is discontinued. Current development for this plugin can be found @https://github.com/logstash-plugins/logstash-output-webhdfs. Please test the current version there and see if your error still persists. If so, please open an issue there.
I'm going to close the issue here.
Thanks and take care,
Björn
